---
language: node_js
os: osx
node_js: 
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
script:
  - npm ci
  - npx jest --ci --passWithNoTests
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script: 
        - npm ci
        - npx expo login -u tohoshinki123 -p hiragana1999
        - npx expo publish --non-interactive